name: .NET CI

on:
  push:
    branches:
      - master
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'chore/**'
  pull_request:
    branches:
      - master
      - main
      - develop
  workflow_dispatch: {}   # << ทำให้มีปุ่ม Run workflow ในแท็บ Actions

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      # (ถ้าใช้ LibMan ให้เอา comment ออกสองบรรทัดด้านล่าง)
      # - name: LibMan restore
      #   run: dotnet tool restore && libman restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
